#ifndef __ADHYDRO_H__
#define __ADHYDRO_H__

#include "all.h"

// mesh_element.decl.h needs CProxy_ChannelElement from channel_element.decl.h, but channel_element.decl.h needs CProxy_MeshElement from mesh_element.decl.h.
// This forward declaration breaks the circularity.
class CProxy_ChannelElement;

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wsign-compare"
#include "adhydro.decl.h"
#pragma GCC diagnostic warning "-Wsign-compare"

// An ADHydro object is the main chare of the program.  Execution starts in its
// constructor.
class ADHydro : public CBase_ADHydro
{
  ADHydro_SDAG_CODE
  
public:
  
  // Set the load balancing mode to manual.  We need to wait for a few
  // timesteps to generate load statistics, and then we need to load balance
  // once.  After that we need to load balance very rarely if at all.
  static void setLoadBalancingToManual();
  
  // Constructor.  This is the mainchare constructor where the program starts.
  //
  // Parameters:
  //
  // msg - Charm++ command line arguments message.
  ADHydro(CkArgMsg* msg);
  
  // Charm++ migration constructor.
  //
  // Parameters:
  //
  // msg - Charm++ migration message.
  ADHydro(CkMigrateMessage* msg);
  
  // Destructor.  commandLineArguments needs to be deleted.
  ~ADHydro();
  
  // Pack/unpack method.
  //
  // Parameters:
  //
  // p - Pack/unpack processing object.
  void pup(PUP::er &p);

  // Reduction callback used as a barrier during file manager initialization.
  void fileManagerFirstCallback();
  
  // Finish initialization after the reduction callback indicating the file
  // manager is ready.
  void finishInitialization();

  // If currentTime is less than endTime do a timestep and cause a callback to
  // timestepDone, otherwise exit.
  void doTimestep();
  
  // Check invariant conditions on member variables.  Exit if invariant is
  // violated.  When the invariant check is done will cause a callback to
  // doTimestep.
  void checkInvariant();
  
private:
  
  // Callback for the dtNew reduction at the end of a timestep.
  //
  // Parameters:
  //
  // dtNew - The minimum new timestep requested by any element.
  void timestepDone(double dtNew);
  
  // Chare proxies.
  CProxy_MeshElement    meshProxy;        // Array of mesh elements.
  CProxy_ChannelElement channelProxy;     // Array of channel elements.
  CProxy_FileManager    fileManagerProxy; // Group of file managers.
  
  // I/O information
  CkArgMsg* commandLineArguments; // Contains the input and output directory paths.
  
  // Time information.
  double currentTime;    // Seconds.
  double endTime;        // Seconds.
  double dt;             // Next timestep duration in seconds.
  double nextOutputTime; // Next time in seconds to output to file.
  double outputPeriod;   // Simulation time in seconds between outputting to file.  Zero for output every timestep.
  int    iteration;      // Iteration number to put on all messages this timestep.
};

#endif // __ADHYDRO_H__
