#include "checkpoint_manager.h"
#include "file_manager_NetCDF.h"

// FIXME stubs
static size_t globalNumberOfMeshElements = 2;
static size_t globalNumberOfChannelElements = 2;
static size_t maximumNumberOfMeshNeighbors = 6;
static size_t maximumNumberOfChannelNeighbors = 4;

void localStartAndNumber(size_t& localItemStart, size_t& localNumberOfItems, size_t globalNumberOfItems)
{
    size_t numPes            = CkNumPes();                       // Number of processors.
    size_t myPe              = CkMyPe();                         // The processor of this file manager.
    size_t numberOfFatOwners = globalNumberOfItems % numPes;     // Number of file managers that own one extra item.
    size_t itemsPerFatOwner  = globalNumberOfItems / numPes + 1; // Number of items in each file manager that owns one extra item.
    size_t itemsPerThinOwner = globalNumberOfItems / numPes;     // Number of items in each file manager that does not own one extra item.
    
    if (myPe < numberOfFatOwners)
    {
        // I am a fat owner.
        localItemStart     = myPe * itemsPerFatOwner;
        localNumberOfItems = itemsPerFatOwner;
    }
    else
    {
        // I am a thin owner.
        localItemStart     = (myPe - numberOfFatOwners) * itemsPerThinOwner + numberOfFatOwners * itemsPerFatOwner;
        localNumberOfItems = itemsPerThinOwner;
    }
}
// FIXME end of stubs

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wunused-variable"
#include "checkpoint_manager.def.h"
#pragma GCC diagnostic warning "-Wunused-variable"
