#include "checkpoint_manager.h"
#include "file_manager_NetCDF.h"

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wunused-variable"
#include "checkpoint_manager.def.h"
#pragma GCC diagnostic warning "-Wunused-variable"
