#include "initialization_manager.h"
#include "adhydro.h"

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wunused-variable"
#include "initialization_manager.def.h"
#pragma GCC diagnostic warning "-Wunused-variable"
