#ifndef __ADHYDRO_H__
#define __ADHYDRO_H__

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wsign-compare"
#include "adhydro.decl.h"
#pragma GCC diagnostic warning "-Wsign-compare"

#include "all_charm.h"

// FIXME comment
class ADHydro : public CBase_ADHydro
{
  ADHydro_SDAG_CODE
  
public:
  
  // Global read-only variables to specify map projection.  Currently we only support a sinusoidal projection.
  static double centralMeridian; // Radians.
  static double falseEasting;    // Meters.
  static double falseNorthing;   // Meters.
  
  // Global read-only variables to specify whether to run the simulation in
  // drain down mode.  In this mode, there will be no precipitation, the water
  // level in the channels will be capped at bank-full depth, and calendar date
  // and time will stand still.  Forcing data, sun angle, and other things that
  // depend on absolute time will always be taken from a single point in time
  // specified by drainDownTime.
  static bool   drainDownMode; // If true, run in drain down mode.
  static double drainDownTime; // Seconds since Element::referenceDate.
  
  // Global read-only variable specifies how much to print to the display.
  // Current verbosity levels are:
  //
  // 0 - Error messages only.
  // 1 - Messages about general simulation progress.
  // 2 - Warning messages about situations that may be a problem.
  // 3 - Messages about general simulation progress or warning messages about
  //     situations that may be a problem that just create too many messages
  //     for levels one and two.
  // 4 - Warning messages about situations that are probably ok.
  static int verbosityLevel;
  
  // Calculate latitude and longitude from X,Y coordinates.
  //
  // Returns: true if there is an error, false otherwise.
  //
  // Parameters:
  //
  // x         - X coordinate in meters.
  // y         - Y coordinate in meters.
  // latitude  - Scalar passed by reference will be filled in with latitude in
  //             radians.
  // longitude - Scalar passed by reference will be filled in with longitude in
  //             radians.
  static bool getLatLong(double x, double y, double& latitude, double& longitude);
  
  // Constructor.  This is the mainchare constructor where the program starts.
  //
  // Parameters:
  //
  // msg - Charm++ command line arguments message.
  ADHydro(CkArgMsg* msg);
};

#endif // __ADHYDRO_H__
