#ifndef __ALL_CHARM_H__
#define __ALL_CHARM_H__

// Either all.h or all_charm.h, but not both, should be included in all other
// files.  all.h should be used for non-Charm++ programs.  all_charm.h should
// be used for Charm++ programs.

// Suppress warnings in the The Charm++ autogenerated code.
#pragma GCC diagnostic ignored "-Wsign-compare"
#include <charm++.h>
#pragma GCC diagnostic warning "-Wsign-compare"

// The ADHYDRO_ASSERT macro is used to accomodate the fact that all.h will
// sometimes be used for non-Charm++ programs, but will be included in
// all_charm.h for Charm++ programs.  ADHYDRO_ASSERT is only meant to be used
// inside all.h or any code that might be used sometimes with Charm++ and
// sometimes not.  If you know whether some particular code uses Charm++ or not
// you should not use this macro. Just use assert or CkAssert instead of
// ADHYDRO_ASSERT.
#define ADHYDRO_ASSERT CkAssert

// all_charm.h also includes everything from all.h.
#include "all.h"

PUPbytes(ChannelTypeEnum);

#endif // __ALL_CHARM_H__
